### ISSUE TITLE
Hi, I'm facing some errors

### ISSUE THREAD

**Issue by moluscus** [pluveto/Mathink#1]
Hello, I got this error when launching Mathink, could you help me with this please ?

Traceback (most recent call last):
  File "mathink.py", line 76, in <module>
    if not process_exists("Mathink.GUI.exe"):
  File "mathink.py", line 20, in process_exists
    last_line = output.strip().split('\r\n')[-1]
TypeError: a bytes-like object is required, not 'str'

**Comment by pluveto** [comment]
It seems that variable `output` is returning bytes instead of a string. 

I have no idea about whether this will works, because I've uninstalled related softwares, (mathink.py, line 18) but you can try change `output = subprocess.check_output(call)` to  `output = subprocess.getoutput(call)`. Looking forward to your feedback.

**Comment by moluscus** [comment]
Thank you for your answer, I tried and it raised another malfunction, 

C:\Program Files\Inkscape\lib\python3.8\subprocess.py:942: ResourceWarning: subprocess 908 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback

I'm too dumb at coding unfortunately to solve this without spending a lot of time. Is it something related to my python version or something computer dependent?

**Comment by pluveto** [comment]
Try this new verison: https://github.com/pluveto/Mathink/releases/download/v1.0/extensions.zip

**Comment by moluscus** [comment]
Thank you very much, we are progressing. 

What's happening now is: 
- I have to grant full control access to the file out.svg to make it run, then the preview and edit expression are working fine,
- then i click on apply and this error appears: 
" mathink.py:82: DeprecationWarning: inkex.debug was moved to inkex.utils.debug
  inkex.debug("file not found: " + output_file)
file not found: Mathink/out.d "
- then i close the mathink second window (with the edit and preview) and the file out.svg just disappear from the folder.

Do you know what's happening ?

Thanks a lot !

**Comment by pluveto** [comment]
I made a mistake. `Mathink/out.d` should be `Mathink/out.svg` in `mathink.inx`. New version will be uploaded soon.

**Comment by pluveto** [comment]
https://github.com/pluveto/Mathink/releases/download/v1.1/extensions.zip

**Comment by moluscus** [comment]
This time it worked fine thanks a lot ! But whenever i close the mathink windows my out.svg file just disappear and if i want to use it again i have to copy paste it ... any idea on this ?

**Comment by pluveto** [comment]
> This time it worked fine thanks a lot ! But whenever i close the mathink windows my out.svg file just disappear and if i want to use it again i have to copy paste it ... any idea on this ?

Try to use "Save as svg image file" by menu operations of that window.

**Comment by moluscus** [comment]
Everything works, but only once. When i close the Mathink edit window the out.svg file just disappear from the folder "C:\Program Files\Inkscape\share\inkscape\extensions\Mathink"

**Comment by moluscus** [comment]
I don't know why but it is related to the file permissions. I found a way to make it work by adding write permission only instead of full control.

So now it's working and i'm really glad, thank you a lot for your help on this.

All the best.
